### ISSUE TITLE
Issues from The Master

### ISSUE THREAD

**Issue by TheMaster3558** [sanjay-nagesh/Portfolio#2]
1. There should be a space after `Programmer,` in the home screens title.
2. Not sure if this is an issue but in the `Hobbies/Interests` page I feel like clicking the buttons should do something.
3. In `Hobbies/Interests`, the `My Skills` bars don't match the percentage.

Thats it but I though the ui was really clean.

**Comment by sanjay-nagesh** [comment]
fixed.
